services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public/:/var/www/public/
      - image:/var/www/upload/image/
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: ./docker/web
      target: php
    volumes:
      - ./public/:/var/www/public/
      - image:/var/www/upload/image/

  mysql:
    container_name: mysql
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/conf.d/:/etc/mysql/conf.d/
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d/

volumes:
  mysql:
  image:
